name: run py script to update highscores

on:
    schedule:
        - cron: "0 2,10,18 * * *"  # Runs at midnight, 8 AM, and 4 PM daily GMT+2 (server time) 
        #- cron: "0 3,11,19 * * *"  # DST (GMT+3)
    workflow_dispatch:
        
jobs:
    run-python-script:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Configure Git user
            run: |
              git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
              git config --global user.name "hxxmz"
          - name: Install Dependencies
            run: |
              python -m pip install beautifulsoup4 requests
          - name: Run Python Script
            run: |
              python hzg-highscore-det.py
          - name: Commit and push
            run: |
              git add detective_highscores.json
              git commit -m "Updated Highscores on $(date +%Y-%m-%d)"
              git push origin main
